CREATE TABLE SPRINT(
   ID SERIAL PRIMARY KEY,
   PROJECTNAME VARCHAR (200) NOT NULL,
   NAME VARCHAR (200) NOT NULL,
   STARTDATE VARCHAR (100) NOT NULL,
   ENDDATE VARCHAR (100) NOT NULL,
   CLOSED BOOLEAN NOT NULL
);

CREATE TABLE PRIORITYDETAILS (
   ID SERIAL PRIMARY KEY,
   PROJECTNAME VARCHAR (200) NOT NULL,
   SPRINTNAME VARCHAR (200) NOT NULL,
   ISSUETYPE VARCHAR (100) NOT NULL,
   PRIORITY VARCHAR (100) NOT NULL,
   PRIORITYCOUNT INT NOT NULL
);

CREATE TABLE STORYPOINTMAPPING (
   ID SERIAL PRIMARY KEY,
   PROJECTNAME VARCHAR (200) NOT NULL,
   SPRINTNAME VARCHAR (200) NOT NULL,
   COMMITTEDSP VARCHAR (100) NOT NULL,
   ACCEPTEDSP VARCHAR (100) NOT NULL
);
